import Head from 'next/head';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Button from '../components/Button';
import Heading from '../components/Heading';

export default function Home() {
  return (
    <>
      <Head>
        <title>FastSell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-100 min-h-screen w-full flex items-center justify-center flex-col">
        <h1 className="text-7xl font-bold text-center">
          Ecommerce, made easy.
        </h1>
        <h2 className="text-4xl mt-2 mb-8">
          Quickly and easily setup your own online store
        </h2>
        <div className="flex items-center justify-center gap-2">
          <Link href={`/auth/sign-in`}>
            <Button size="xl" appearance="primary" type="button">
              Sign In
            </Button>
          </Link>
          <Link href={`/auth/sign-up`}>
            <Button size="xl" appearance="outline" type="button">
              Sign Up
            </Button>
          </Link>
        </div>
      </div>
    </>
  );
}
